services:
  ipx-server:
    build: .
    image: my-ipx-server-app
    container_name: ipx_server_prod
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 150M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:4321/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s